type TranslationMap = { [english: string]: string };

export const translations: TranslationMap = {
  // Expense fields (all lowercase, snake case)
  expense_id: "ID de Gasto",
  date: "Fecha",
  user_name: "Nombre de Usuario",
  paid_through_account_name: "Cuenta de Pago",
  account_name: "Nombre de Cuenta",
  description: "Descripción",
  currency_id: "ID de Moneda",
  currency_code: "Código de Moneda",
  bcy_total: "Total Bcy",
  bcy_total_without_tax: "Total Bcy sin Impuesto",
  total: "Total",
  total_without_tax: "Total sin Impuesto",
  is_billable: "Facturable",
  reference_number: "Número de Referencia",
  customer_id: "ID de Cliente",
  is_personal: "Personal",
  customer_name: "Nombre de Cliente",
  vendor_id: "ID de Proveedor",
  vendor_name: "Nombre del Proveedor",
  status: "Estado",
  created_time: "Fecha de Creación",
  last_modified_time: "Fecha de Última Modificación",
  expense_receipt_name: "Nombre del Recibo",
  exchange_rate: "Tasa de Cambio",
  distance: "Distancia",
  mileage_rate: "Tarifa de Kilometraje",
  mileage_unit: "Unidad de Kilometraje",
  mileage_type: "Tipo de Kilometraje",
  expense_type: "Tipo de Gasto",
  report_id: "ID de Reporte",
  start_reading: "Lectura Inicial",
  end_reading: "Lectura Final",
  report_name: "Nombre de Reporte",
  report_number: "Número de Reporte",
  has_attachment: "Tiene Adjunto",
  custom_fields_list: "Lista de Campos Personalizados",
  actions: "Acciones",

  // Invoice fields (snake case)
  ach_payment_initiated: "Pago ACH Iniciado",
  invoice_id: "ID de Factura",
  zcrm_potential_id: "ID de Potencial (ZCRM)",
  zcrm_potential_name: "Nombre de Potencial (ZCRM)",
  company_name: "Nombre de Empresa",
  invoice_number: "Número de Factura",
  due_date: "Fecha de Vencimiento",
  due_days: "Días de Vencimiento",
  email: "Correo",
  project_name: "Nombre de Proyecto",
  billing_address: "Dirección de Facturación",
  shipping_address: "Dirección de Envío",
  country: "País",
  phone: "Teléfono",
  created_by: "Creado por",
  balance: "Balance",
  payment_expected_date: "Fecha de Pago Esperada",
  custom_fields: "Campos Personalizados",
  custom_field_hash: "Hash de Campos Personalizados",
  tags: "Etiquetas",
  salesperson_name: "Nombre de Vendedor",
  shipping_charge: "Cargo de Envío",
  adjustment: "Ajuste",
  updated_time: "Fecha de Actualización",
  is_viewed_by_client: "Visto por Cliente",
  client_viewed_time: "Fecha de Visualización del Cliente",
  is_emailed: "Enviado por Correo",
  color_code: "Código de Color",
  current_sub_status_id: "ID de Subestado Actual",
  current_sub_status: "Subestado Actual",
  schedule_time: "Fecha Programada",
  currency_symbol: "Símbolo de Moneda",
  template_type: "Tipo de Plantilla",
  no_of_copies: "Número de Copias",
  show_no_of_copies: "Mostrar Número de Copias",
  invoice_url: "URL de Factura",
  transaction_type: "Tipo de Transacción",
  reminders_sent: "Recordatorios Enviados",
  last_reminder_sent_date: "Fecha del Último Recordatorio",
  last_payment_date: "Fecha del Último Pago",
  template_id: "ID de Plantilla",
  documents: "Documentos",
  salesperson_id: "ID de Vendedor",
  write_off_amount: "Monto Anulado",
  unprocessed_payment_amount: "Monto de Pago No Procesado",

  // Additional old fields
  id: "ID",
  source: "Fuente",
  lawyer: "Abogado",
  amount: "Monto",
  disbursement_type: "Tipo de Desembolso",
};

/**
 * Translates an English (snake case) column name to Spanish if found in the map.
 * Returns the original if no translation is found.
 */
export function getSpanishTitle(englishTitle: string): string {
  return translations[englishTitle] || englishTitle;
}
